"""Dash front-end for `main_lstm.py` (train/evaluate) and `optimize_hyperparams.py`
(hyperparameter search via differential evolution).

Each tab's form is generated by introspecting that script's own
`argparse.ArgumentParser` (via `build_parser()`), so every CLI parameter is
exposed automatically and the UI can't drift out of sync with the scripts as
they evolve — nothing about individual flags is hardcoded here. Runs execute
in a background thread (training/search can take a while); a polling
`dcc.Interval` streams the captured log output back to the browser and shows
the resulting plots/results table once the run finishes.

Run:
    uv run python dashboard.py
Then open http://127.0.0.1:8050/
"""

from __future__ import annotations

import argparse
import base64
import logging
import re
import threading
import traceback
from pathlib import Path
from typing import Any, Callable

import pandas as pd
from dash import ALL, Dash, Input, Output, State, dcc, html

import main_lstm
import optimize_hyperparams
from fx_forecasting.data.fx_downloader import MAJOR_FX_PAIRS
from fx_forecasting.hparam_search import DEFAULT_PARAM_SPECS, best_plot_path_for

logger = logging.getLogger(__name__)

PAIR_OPTIONS = [{"label": p, "value": p} for p in MAJOR_FX_PAIRS]
PARAM_OPTIONS = [{"label": s.name, "value": s.name} for s in DEFAULT_PARAM_SPECS]

EPOCH_LOG_RE = re.compile(r"epoch\s+(\d+)/(\d+)")

# ----------------------------------------------------------------------------
# Background job execution
# ----------------------------------------------------------------------------


class ListLogHandler(logging.Handler):
    """Appends formatted log records to a plain list, polled by the UI."""

    def __init__(self, sink: list[str]) -> None:
        super().__init__()
        self.sink = sink
        self.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))

    def emit(self, record: logging.LogRecord) -> None:
        self.sink.append(self.format(record))


RUN_STATE: dict[str, dict[str, Any]] = {
    "train": {"thread": None, "logs": [], "running": False, "error": None, "artifacts": {}, "cancelled": False},
    "optimize": {
        "thread": None,
        "logs": [],
        "running": False,
        "error": None,
        "artifacts": {},
        "progress_total_estimate": None,
        "cancelled": False,
    },
}

# Each mode's cooperative-cancellation flag, checked from inside the running
# job itself (main_lstm.train()'s epoch loop / optimize_hyperparams's DE
# objective) — a thread can't be safely force-killed, so Stop just requests
# cancellation at the next safe checkpoint rather than stopping instantly.
CANCEL_EVENTS: dict[str, threading.Event] = {
    "train": main_lstm.CANCEL_EVENT,
    "optimize": optimize_hyperparams.CANCEL_EVENT,
}


def run_job(mode: str, entry_fn: Callable[[list[str] | None], None], argv: list[str]) -> None:
    state = RUN_STATE[mode]
    handler = ListLogHandler(state["logs"])
    root_logger = logging.getLogger()
    root_logger.addHandler(handler)
    root_logger.setLevel(logging.INFO)
    state["logs"].append("$ " + " ".join(argv))
    try:
        entry_fn(argv)
    except SystemExit as e:
        if not state["cancelled"]:
            state["error"] = f"Argument error (exit code {e.code}) — check the log above."
    except Exception as e:  # noqa: BLE001 — surface any failure to the UI rather than losing it
        if state["cancelled"]:
            # Both scripts cancel gracefully (main_lstm.train() breaks its epoch loop;
            # optimize_hyperparams's DE callback returns True) — entry_fn returns
            # normally rather than raising, so this branch is a defensive fallback,
            # not the expected path for a user-requested stop.
            state["logs"].append(f"{type(e).__name__}: {e} (occurred while a stop was requested)")
        else:
            state["error"] = f"{type(e).__name__}: {e}"
            state["logs"].append(traceback.format_exc())
    finally:
        root_logger.removeHandler(handler)
        state["running"] = False


def start_job(mode: str, entry_fn: Callable[[list[str] | None], None], argv: list[str]) -> None:
    state = RUN_STATE[mode]
    if state["running"]:
        return
    CANCEL_EVENTS[mode].clear()
    state.update(
        thread=None, logs=[], running=True, error=None, artifacts={}, progress_total_estimate=None, cancelled=False
    )
    thread = threading.Thread(target=run_job, args=(mode, entry_fn, argv), daemon=True)
    state["thread"] = thread
    thread.start()


def stop_job(mode: str) -> None:
    """Requests cancellation of the running job for `mode`; takes effect at the next
    safe checkpoint inside the job (not instantly — see `CANCEL_EVENTS`)."""
    state = RUN_STATE[mode]
    if state["running"]:
        state["cancelled"] = True
        CANCEL_EVENTS[mode].set()


def resolve_default(parser: argparse.ArgumentParser, dest: str) -> Any:
    for action in parser._actions:  # noqa: SLF001 — argparse has no public accessor for this
        if action.dest == dest:
            return action.default
    return None


def build_argv(parser: argparse.ArgumentParser, values: dict[str, Any]) -> list[str]:
    """Turns {dest: form_value} into a CLI argv list, letting empty fields fall back to
    each flag's own script default (by simply omitting that flag)."""
    argv: list[str] = []
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action, argparse._HelpAction):  # noqa: SLF001
            continue
        dest = action.dest
        if dest not in values:
            continue
        value = values[dest]
        flag = action.option_strings[0]

        if isinstance(action, argparse._StoreTrueAction):  # noqa: SLF001
            if value:  # dcc.Checklist value is a list, e.g. ["on"] or []
                argv.append(flag)
            continue

        if value is None or value == "" or value == []:
            continue

        if action.nargs == "+":
            argv.append(flag)
            argv.extend(str(v) for v in value)
            continue

        argv.append(flag)
        argv.append(str(value))
    return argv


def encode_image(path: str | None) -> str | None:
    if not path:
        return None
    p = Path(path)
    if not p.exists():
        return None
    return "data:image/png;base64," + base64.b64encode(p.read_bytes()).decode("ascii")


def render_progress_bar(label: str, percent: float | None):
    """A minimal CSS progress bar — Dash core components has no built-in one."""
    if percent is None:
        return html.Div()
    percent = max(0.0, min(100.0, percent))
    return html.Div(
        [
            html.Div(label, style={"fontSize": "0.8rem", "marginBottom": "3px"}),
            html.Div(
                html.Div(
                    style={
                        "width": f"{percent}%",
                        "background": "#2b8a3e",
                        "height": "100%",
                        "borderRadius": "4px",
                        "transition": "width 0.4s ease",
                    }
                ),
                style={
                    "background": "#e0e0e0",
                    "height": "14px",
                    "borderRadius": "4px",
                    "overflow": "hidden",
                    "width": "100%",
                },
            ),
        ],
        style={"margin": "8px 0", "maxWidth": "420px"},
    )


def train_progress(state: dict[str, Any]):
    """Parses the last "epoch N/M" log line — --epochs is the exact, known denominator."""
    for line in reversed(state["logs"]):
        m = EPOCH_LOG_RE.search(line)
        if m:
            current, total = int(m.group(1)), int(m.group(2))
            return render_progress_bar(f"Epoch {current}/{total}", 100.0 * current / total)
    return html.Div()


def optimize_progress(state: dict[str, Any]):
    """Progress derived from the results CSV's row count, not the captured log text.

    With `--workers` > 1, each trial runs in a separate worker *process*
    (scipy's DE multiprocessing) — those processes have no logging handler
    attached (only the main process does, via `ListLogHandler`), so per-trial
    "trial N: ..." log lines never reach `state["logs"]` and a log-based
    progress bar would silently never move. The results CSV, on the other
    hand, is appended to directly by every worker regardless of process
    boundary (see `optimize_hyperparams.append_trial_row`), so it's the one
    reliable, process-agnostic signal for "how many trials have finished so
    far". Total trial count is only an estimate (DE's exact evaluation count
    depends on convergence), hence the "~".
    """
    csv_path = state.get("artifacts", {}).get("results_csv")
    if not csv_path or not Path(csv_path).exists():
        return html.Div()
    try:
        with open(csv_path, newline="") as f:
            current = sum(1 for _ in f) - 1  # total lines minus the header row
    except OSError:
        return html.Div()
    if current < 0:
        return html.Div()

    total = state.get("progress_total_estimate")
    if not total:
        return html.Div(f"Trial {current}")
    return render_progress_bar(f"Trial {current} / ~{total}", 100.0 * current / total)


# ----------------------------------------------------------------------------
# Form generation (driven entirely by argparse introspection)
# ----------------------------------------------------------------------------


def field_component(action: argparse.Action, id_prefix: str):
    dest = action.dest
    comp_id = {"type": f"{id_prefix}-field", "dest": dest}

    if isinstance(action, argparse._StoreTrueAction):  # noqa: SLF001
        return dcc.Checklist(id=comp_id, options=[{"label": " enabled", "value": "on"}], value=[])

    if action.choices:
        return dcc.Dropdown(id=comp_id, options=list(action.choices), value=action.default, clearable=False)

    if action.nargs == "+":
        options = PAIR_OPTIONS if dest == "pairs" else PARAM_OPTIONS if dest == "params" else []
        return dcc.Dropdown(id=comp_id, options=options, value=action.default or [], multi=True)

    if action.type in (int, float):
        return dcc.Input(
            id=comp_id, type="number", value=action.default, step="any", style={"width": "100%"}
        )

    return dcc.Input(
        id=comp_id,
        type="text",
        value=action.default if action.default is not None else "",
        placeholder=str(action.default) if action.default is not None else "",
        style={"width": "100%"},
    )


def build_form(parser: argparse.ArgumentParser, id_prefix: str) -> list:
    cells = []
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action, argparse._HelpAction):  # noqa: SLF001
            continue
        flag = action.option_strings[0]
        cells.append(
            html.Div(
                [
                    html.Label(flag, style={"fontWeight": "600", "fontSize": "0.85rem"}),
                    field_component(action, id_prefix),
                    html.Div(action.help or "", style={"fontSize": "0.72rem", "color": "#666", "marginTop": "2px"}),
                ],
                style={"padding": "8px"},
            )
        )
    return cells


# ----------------------------------------------------------------------------
# Layout
# ----------------------------------------------------------------------------

GRID_STYLE = {"display": "grid", "gridTemplateColumns": "repeat(3, 1fr)", "gap": "4px"}
LOG_STYLE = {
    "background": "#111",
    "color": "#ddd",
    "fontFamily": "monospace",
    "fontSize": "0.75rem",
    "padding": "10px",
    "height": "260px",
    "overflowY": "auto",
    "whiteSpace": "pre-wrap",
}

train_parser = main_lstm.build_parser()
optimize_parser = optimize_hyperparams.build_parser()

app = Dash(__name__)
app.title = "FX Forecasting"

app.layout = html.Div(
    [
        html.H2("FX Forecasting"),
        dcc.Tabs(
            [
                dcc.Tab(
                    label="Train / Evaluate",
                    children=[
                        html.Div(build_form(train_parser, "train"), style=GRID_STYLE),
                        html.Button("Run training", id="train-run-btn", n_clicks=0, style={"marginTop": "10px"}),
                        html.Button(
                            "Stop", id="train-stop-btn", n_clicks=0, style={"marginTop": "10px", "marginLeft": "6px"}
                        ),
                        html.Span(id="train-status", style={"marginLeft": "10px", "fontWeight": "600"}),
                        html.Div(id="train-progress"),
                        html.Pre(id="train-log", style=LOG_STYLE),
                        html.Div(id="train-artifacts"),
                        dcc.Interval(id="train-interval", interval=1000, disabled=True),
                    ],
                ),
                dcc.Tab(
                    label="Hyperparameter Search",
                    children=[
                        html.Div(build_form(optimize_parser, "optimize"), style=GRID_STYLE),
                        html.Button(
                            "Run search", id="optimize-run-btn", n_clicks=0, style={"marginTop": "10px"}
                        ),
                        html.Button(
                            "Stop",
                            id="optimize-stop-btn",
                            n_clicks=0,
                            style={"marginTop": "10px", "marginLeft": "6px"},
                        ),
                        html.Span(id="optimize-status", style={"marginLeft": "10px", "fontWeight": "600"}),
                        html.Div(id="optimize-progress"),
                        html.Pre(id="optimize-log", style=LOG_STYLE),
                        html.Div(id="optimize-artifacts"),
                        dcc.Interval(id="optimize-interval", interval=1000, disabled=True),
                    ],
                ),
            ]
        ),
    ],
    style={"maxWidth": "1200px", "margin": "0 auto", "padding": "20px", "fontFamily": "sans-serif"},
)


# ----------------------------------------------------------------------------
# Callbacks
# ----------------------------------------------------------------------------


def register_run_callback(mode: str, parser: argparse.ArgumentParser, entry_fn) -> None:
    @app.callback(
        Output(f"{mode}-interval", "disabled"),
        Output(f"{mode}-status", "children"),
        Input(f"{mode}-run-btn", "n_clicks"),
        State({"type": f"{mode}-field", "dest": ALL}, "value"),
        State({"type": f"{mode}-field", "dest": ALL}, "id"),
        prevent_initial_call=True,
    )
    def on_run(n_clicks, values, ids):  # noqa: ANN001, ARG001
        if RUN_STATE[mode]["running"]:
            return False, "Already running…"
        value_map = {id_["dest"]: v for id_, v in zip(ids, values)}
        argv = build_argv(parser, value_map)

        artifacts: dict[str, str] = {}
        if mode == "train":
            artifacts["plot_path"] = value_map.get("plot_path") or resolve_default(parser, "plot_path")
            artifacts["in_sample_plot_path"] = value_map.get("in_sample_plot_path") or resolve_default(
                parser, "in_sample_plot_path"
            )
            artifacts["pnl_plot_path"] = value_map.get("pnl_plot_path") or resolve_default(parser, "pnl_plot_path")
        else:
            results_csv = value_map.get("load") or value_map.get("results_csv") or resolve_default(
                parser, "results_csv"
            )
            artifacts["results_csv"] = results_csv
            artifacts["best_plot_path"] = best_plot_path_for(results_csv) if results_csv else None

        start_job(mode, entry_fn, argv)
        RUN_STATE[mode]["artifacts"] = artifacts

        if mode == "optimize":
            # DE evaluates the objective ~popsize * num_params times per generation,
            # across maxiter+1 generations — an estimate (exact count depends on
            # convergence), used only to label the progress bar with "~".
            num_params = len(value_map.get("params") or [s.name for s in DEFAULT_PARAM_SPECS])
            popsize = int(value_map.get("popsize") or resolve_default(parser, "popsize"))
            maxiter = int(value_map.get("maxiter") or resolve_default(parser, "maxiter"))
            RUN_STATE[mode]["progress_total_estimate"] = popsize * num_params * (maxiter + 1)

        return False, "Running…"


register_run_callback("train", train_parser, main_lstm.main)
register_run_callback("optimize", optimize_parser, optimize_hyperparams.main)


def register_stop_callback(mode: str) -> None:
    @app.callback(
        Output(f"{mode}-status", "children", allow_duplicate=True),
        Input(f"{mode}-stop-btn", "n_clicks"),
        prevent_initial_call=True,
    )
    def on_stop(n_clicks):  # noqa: ANN001, ARG001
        if not RUN_STATE[mode]["running"]:
            return "Idle."
        stop_job(mode)
        return "Stopping…"


register_stop_callback("train")
register_stop_callback("optimize")


def render_train_artifacts(artifacts: dict[str, str]) -> list:
    children = []
    for key, title in (
        ("plot_path", "Out-of-sample (validation) predictions"),
        ("in_sample_plot_path", "In-sample (training) predictions"),
        ("pnl_plot_path", "Strategy PnL (out-of-sample)"),
    ):
        src = encode_image(artifacts.get(key))
        if src:
            children.append(html.H4(title))
            children.append(html.Img(src=src, style={"maxWidth": "100%"}))
    return children


def render_optimize_artifacts(artifacts: dict[str, str]) -> list:
    """Best-trial-so-far predictions plot (updated live by `optimize_hyperparams.
    maybe_save_best_prediction_plot` whenever a trial beats every prior one), then the
    top-10-by-loss table from the results CSV — both refreshed on every poll tick,
    including while the search is still running (see `register_poll_callback`)."""
    children = []

    best_plot_src = encode_image(artifacts.get("best_plot_path"))
    if best_plot_src:
        children.append(html.H4("Best trial so far — out-of-sample predictions"))
        children.append(html.Img(src=best_plot_src, style={"maxWidth": "100%"}))

    csv_path = artifacts.get("results_csv")
    if not csv_path or not Path(csv_path).exists():
        return children
    try:
        df = pd.read_csv(csv_path)
    except Exception:  # noqa: BLE001
        return children
    df = df[df["status"] == "ok"].sort_values("loss").head(10)
    if df.empty:
        children.append(html.Div("No successful trials in results CSV yet."))
        return children

    header = html.Tr([html.Th(c) for c in df.columns])
    rows = [html.Tr([html.Td(f"{v:.4g}" if isinstance(v, float) else v) for v in row]) for row in df.itertuples(index=False)]
    children.append(html.H4(f"Top {len(df)} trials — {csv_path}"))
    children.append(
        html.Table(
            [html.Thead(header), html.Tbody(rows)],
            style={"fontSize": "0.8rem", "borderCollapse": "collapse", "width": "100%"},
        )
    )
    return children


def register_poll_callback(mode: str, render_artifacts, progress_fn) -> None:
    @app.callback(
        Output(f"{mode}-log", "children"),
        Output(f"{mode}-status", "children", allow_duplicate=True),
        Output(f"{mode}-interval", "disabled", allow_duplicate=True),
        Output(f"{mode}-artifacts", "children"),
        Output(f"{mode}-progress", "children"),
        Input(f"{mode}-interval", "n_intervals"),
        prevent_initial_call=True,
    )
    def on_tick(_n_intervals):  # noqa: ANN001
        state = RUN_STATE[mode]
        log_text = "\n".join(state["logs"])
        progress = progress_fn(state)
        # Rendered every tick, running or not, so e.g. optimize_hyperparams's
        # best-trial-so-far plot updates live during a long search rather than
        # only appearing once the whole run finishes.
        artifacts_children = render_artifacts(state["artifacts"])
        if state["running"]:
            status = "Stopping…" if state["cancelled"] else "Running…"
            return log_text, status, False, artifacts_children, progress

        if state["cancelled"]:
            status = "Stopped by user."
        elif state["error"]:
            status = f"Failed: {state['error']}"
        else:
            status = "Done."
        return log_text, status, True, artifacts_children, progress


register_poll_callback("train", render_train_artifacts, train_progress)
register_poll_callback("optimize", render_optimize_artifacts, optimize_progress)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    app.run(debug=False, host="127.0.0.1", port=8050)
